$PROBLEM 1

$INPUT C ID AMT RATE DUR TIME DV MDV EVID WT PMA SEXM 

$DATA example1_g.CSV IGNORE=C

$SUBROUTINES ADVAN5 

$MODEL
COMP(CENTRAL1,DEFDOSE,DEFOBS)
{NCMT}

$PK
DUMMY = ETA(1)
   TVCL=THETA(1)  {WTonCL} {PMAonCL} {SEXMonCL} {IIVonCL}
   CL=TVCL 
   TVV=THETA(2)   {WTonV} {PMAonV} {SEXMonV} {IIVonV}
   V=TVV 
   K10 = CL/V
   S1=V
   D1=DUR
{NCMT}
 
$ERROR
 IPRED = F
 IRES = DV-IPRED
 W = SQRT(IPRED**2 * SIGMA(1,1) + SIGMA(2,2))
 IWRES = IRES/W
 
 Y = IPRED + IPRED*EPS(1) + EPS(2)
 
$ESTIMATION METHOD=1 INTERACTION PRINT=5 MAX=9999 MSFO=1.MSF NOABORT

$THETA 
  (0 0.3) ;CL
  (0 3)   ;V
 {WTonCL} 
{PMAonCL} 
{SEXMonCL}
 {WTonV} 
{PMAonV}
 {SEXMonV}
{NCMT}
   
$OMEGA
(0 FIX) ; DUMMY
{IIVonCL}
{IIVonV}

$SIGMA
  0.3   ;Prop
  0 FIX ;Add

$COVARIANCE PRINT=E

$TABLE ID TIME AMT MDV EVID CL V IPRED IWRES CWRESI CWRES WT PMA SEXM ONEHEADER NOPRINT FILE=mytab1
$TABLE ID TIME MDV EVID IPRED IWRES CWRESI ONEHEADER NOPRINT FILE=sdtab1
$TABLE ID CL V ALLETAS ONEHEADER NOPRINT NOAPPEND FILE=patab1
$TABLE ID WT PMA ONEHEADER NOPRINT NOAPPEND FILE=cotab1
$TABLE ID SEXM ONEHEADER NOPRINT NOAPPEND FILE=catab1
